# Generated by Django 5.1 on 2024-08-21 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('descricao', models.TextField(blank=True)),
                ('participantes', models.ManyToManyField(related_name='reunioes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
