# Generated by Django 5.1 on 2024-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='duracao',
            field=models.CharField(default='30min', max_length=10),
        ),
    ]
