# Generated by Django 4.2.15 on 2024-08-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='profile_image',
            field=models.TextField(default='C:\\Users\\Usuario\\Documents\\my_studies\\projeto-coresync\\coresync\\backend\\media\\profile\\profile_image_default', verbose_name=False),
        ),
    ]
