<<<<<<< HEAD
# Generated by Django 5.1 on 2024-08-28 10:41
=======
# Generated by Django 4.2.15 on 2024-08-28 11:21
>>>>>>> 596d175ab645fbc9297dbac2905a6af721d3a0c6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_alter_profileimage_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='profile_image',
<<<<<<< HEAD
            field=models.TextField(default='C:\\Users\\LID2JVL\\Documents\\estudos\\projetos\\coresync\\coresync\\backend\\media\\profile\\profile_image_default.png', verbose_name=False),
=======
            field=models.TextField(default='C:\\Users\\Usuario\\Documents\\my_studies\\projeto-coresync\\coresync\\backend\\media\\profile\\profile_image_default.png', verbose_name=False),
>>>>>>> 596d175ab645fbc9297dbac2905a6af721d3a0c6
        ),
    ]
