# Generated by Django 4.2.15 on 2024-08-22 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingstatus',
            name='training',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='training.training'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In progress'), ('complete', 'Complete')], default='pending', max_length=20),
        ),
    ]
